import { defineObject, FieldType } from 'twenty-sdk/define';
import {
  CALL_EVENT_ANSWERED_BY_FIELD_UNIVERSAL_IDENTIFIER,
  CALL_EVENT_DIRECTION_FIELD_UNIVERSAL_IDENTIFIER,
  CALL_EVENT_DURATION_FIELD_UNIVERSAL_IDENTIFIER,
  CALL_EVENT_ENDED_AT_FIELD_UNIVERSAL_IDENTIFIER,
  CALL_EVENT_EXTERNAL_SOURCE_ID_FIELD_UNIVERSAL_IDENTIFIER,
  CALL_EVENT_FROM_NUMBER_FIELD_UNIVERSAL_IDENTIFIER,
  CALL_EVENT_PARENT_CALL_ID_FIELD_UNIVERSAL_IDENTIFIER,
  CALL_EVENT_PAYLOAD_HASH_FIELD_UNIVERSAL_IDENTIFIER,
  CALL_EVENT_PROVIDER_CALL_ID_FIELD_UNIVERSAL_IDENTIFIER,
  CALL_EVENT_PROVIDER_ERROR_FIELD_UNIVERSAL_IDENTIFIER,
  CALL_EVENT_PROVIDER_EVENT_TYPE_FIELD_UNIVERSAL_IDENTIFIER,
  CALL_EVENT_PROVIDER_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
  CALL_EVENT_STARTED_AT_FIELD_UNIVERSAL_IDENTIFIER,
  CALL_EVENT_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
  CALL_EVENT_TO_NUMBER_FIELD_UNIVERSAL_IDENTIFIER,
  CALL_EVENT_UNIVERSAL_IDENTIFIER,
} from '../constants';

export default defineObject({
  universalIdentifier: CALL_EVENT_UNIVERSAL_IDENTIFIER,
  nameSingular: 'callEvent',
  namePlural: 'callEvents',
  labelSingular: 'Call event',
  labelPlural: 'Call history',
  description: 'A normalized Sinch Voice call event without media, recordings, or raw callback payloads.',
  icon: 'IconPhoneCall',
  labelIdentifierFieldMetadataUniversalIdentifier: CALL_EVENT_PROVIDER_CALL_ID_FIELD_UNIVERSAL_IDENTIFIER,
  fields: [
    { universalIdentifier: CALL_EVENT_PROVIDER_CALL_ID_FIELD_UNIVERSAL_IDENTIFIER, type: FieldType.TEXT, name: 'providerCallId', label: 'Provider call ID', icon: 'IconHash', isUnique: true },
    { universalIdentifier: CALL_EVENT_PARENT_CALL_ID_FIELD_UNIVERSAL_IDENTIFIER, type: FieldType.TEXT, name: 'parentCallId', label: 'Parent call ID', icon: 'IconGitBranch', isNullable: true },
    { universalIdentifier: CALL_EVENT_FROM_NUMBER_FIELD_UNIVERSAL_IDENTIFIER, type: FieldType.PHONES, name: 'fromNumber', label: 'From', icon: 'IconPhone', isNullable: true },
    { universalIdentifier: CALL_EVENT_TO_NUMBER_FIELD_UNIVERSAL_IDENTIFIER, type: FieldType.PHONES, name: 'toNumber', label: 'To', icon: 'IconPhone', isNullable: true },
    { universalIdentifier: CALL_EVENT_DIRECTION_FIELD_UNIVERSAL_IDENTIFIER, type: FieldType.SELECT, name: 'direction', label: 'Direction', icon: 'IconArrowsExchange', options: [{ id: '8f3b5b2d-787c-49c9-8ceb-cf046aa0ca5c', label: 'Inbound', value: 'INBOUND', position: 0, color: 'blue' }, { id: 'a72d3155-ee30-4f37-a146-57d87276db36', label: 'Outbound', value: 'OUTBOUND', position: 1, color: 'green' }] },
    { universalIdentifier: CALL_EVENT_STATUS_FIELD_UNIVERSAL_IDENTIFIER, type: FieldType.SELECT, name: 'status', label: 'Status', icon: 'IconPhoneCheck', options: [{ id: '47f6c047-c7ac-4aeb-82d6-a92dcc7de1f5', label: 'Ringing', value: 'RINGING', position: 0, color: 'yellow' }, { id: 'c35f2718-4b9c-407a-b901-95ad807193fe', label: 'Answered', value: 'ANSWERED', position: 1, color: 'blue' }, { id: '074a2ac8-5d39-468e-bb70-82b090ee1633', label: 'Completed', value: 'COMPLETED', position: 2, color: 'green' }, { id: '8c86bbcf-d46c-4f0d-bce0-b022d0721761', label: 'Missed', value: 'MISSED', position: 3, color: 'orange' }, { id: '851f1288-cd49-4c65-824f-a233370da1dc', label: 'Failed', value: 'FAILED', position: 4, color: 'red' }] },
    { universalIdentifier: CALL_EVENT_PROVIDER_STATUS_FIELD_UNIVERSAL_IDENTIFIER, type: FieldType.TEXT, name: 'providerStatus', label: 'Provider status', icon: 'IconInfoCircle', isNullable: true },
    { universalIdentifier: CALL_EVENT_DURATION_FIELD_UNIVERSAL_IDENTIFIER, type: FieldType.NUMBER, name: 'durationSeconds', label: 'Duration (seconds)', icon: 'IconClock', isNullable: true },
    { universalIdentifier: CALL_EVENT_ANSWERED_BY_FIELD_UNIVERSAL_IDENTIFIER, type: FieldType.TEXT, name: 'answeredBy', label: 'Answered by', icon: 'IconUserCheck', isNullable: true },
    { universalIdentifier: CALL_EVENT_STARTED_AT_FIELD_UNIVERSAL_IDENTIFIER, type: FieldType.DATE_TIME, name: 'startedAt', label: 'Started at', icon: 'IconCalendarPlay', isNullable: true },
    { universalIdentifier: CALL_EVENT_ENDED_AT_FIELD_UNIVERSAL_IDENTIFIER, type: FieldType.DATE_TIME, name: 'endedAt', label: 'Ended at', icon: 'IconCalendarCheck', isNullable: true },
    { universalIdentifier: CALL_EVENT_PROVIDER_EVENT_TYPE_FIELD_UNIVERSAL_IDENTIFIER, type: FieldType.TEXT, name: 'providerEventType', label: 'Provider event type', icon: 'IconBell', isNullable: true },
    { universalIdentifier: CALL_EVENT_PROVIDER_ERROR_FIELD_UNIVERSAL_IDENTIFIER, type: FieldType.TEXT, name: 'providerError', label: 'Provider error', icon: 'IconAlertTriangle', isNullable: true },
    { universalIdentifier: CALL_EVENT_PAYLOAD_HASH_FIELD_UNIVERSAL_IDENTIFIER, type: FieldType.TEXT, name: 'payloadHash', label: 'Payload hash', icon: 'IconShieldCheck', isNullable: true },
    { universalIdentifier: CALL_EVENT_EXTERNAL_SOURCE_ID_FIELD_UNIVERSAL_IDENTIFIER, type: FieldType.TEXT, name: 'externalSourceId', label: 'External source ID', icon: 'IconDatabase', isNullable: true },
  ],
});
