import { defineIndex } from 'twenty-sdk/define';
import { SMS_MESSAGE_OBJECT_UNIVERSAL_IDENTIFIER, SMS_MESSAGE_PROVIDER_ID_FIELD_UNIVERSAL_IDENTIFIER, SMS_MESSAGE_PROVIDER_ID_INDEX_FIELD_UNIVERSAL_IDENTIFIER, SMS_MESSAGE_PROVIDER_ID_INDEX_UNIVERSAL_IDENTIFIER } from 'src/constants/universal-identifiers';

export default defineIndex({ universalIdentifier: SMS_MESSAGE_PROVIDER_ID_INDEX_UNIVERSAL_IDENTIFIER, objectUniversalIdentifier: SMS_MESSAGE_OBJECT_UNIVERSAL_IDENTIFIER, isUnique: true, fields: [{ universalIdentifier: SMS_MESSAGE_PROVIDER_ID_INDEX_FIELD_UNIVERSAL_IDENTIFIER, fieldUniversalIdentifier: SMS_MESSAGE_PROVIDER_ID_FIELD_UNIVERSAL_IDENTIFIER }] });
