import { defineIndex } from 'twenty-sdk/define';
import { SMS_CONSENT_DEDUPE_KEY_FIELD_UNIVERSAL_IDENTIFIER, SMS_CONSENT_DEDUPE_KEY_INDEX_FIELD_UNIVERSAL_IDENTIFIER, SMS_CONSENT_DEDUPE_KEY_INDEX_UNIVERSAL_IDENTIFIER, SMS_CONSENT_EVENT_OBJECT_UNIVERSAL_IDENTIFIER } from 'src/constants/universal-identifiers';

export default defineIndex({ universalIdentifier: SMS_CONSENT_DEDUPE_KEY_INDEX_UNIVERSAL_IDENTIFIER, objectUniversalIdentifier: SMS_CONSENT_EVENT_OBJECT_UNIVERSAL_IDENTIFIER, isUnique: true, fields: [{ universalIdentifier: SMS_CONSENT_DEDUPE_KEY_INDEX_FIELD_UNIVERSAL_IDENTIFIER, fieldUniversalIdentifier: SMS_CONSENT_DEDUPE_KEY_FIELD_UNIVERSAL_IDENTIFIER }] });
